// Import the Buffer class from Node.js's buffer module
const { Buffer } = require('node:buffer');

// Create a Buffer containing three bytes: 10, 200, and 255
const buf = Buffer.from([10, 200, 255]);

// Read the unsigned 8-bit integer at offset 0
console.log('Byte 0:', buf.readUInt8(0));

// Read the unsigned 8-bit integer at offset 1
console.log('Byte 1:', buf.readUInt8(1));

// Read the unsigned 8-bit integer at offset 2
console.log('Byte 2:', buf.readUInt8(2));

try {
    // Attempt to read a 16-bit unsigned integer in Big-Endian format
    // starting at offset 3. This will fail because there are not
    // enough bytes available in the buffer.
    console.log(buf.readUInt16BE(3));
} catch (err) {
    // Display the error code generated by Node.js
    console.error('Error:', err.code);
}