#include <node_api.h>
#include <thread>
#include <string>
#include <cstdio>

/*
 * Structure used to store data that will be shared between
 * the asynchronous execute callback and the completion callback.
 */
struct WorkData {
    // Stores the result produced by the background operation.
    std::string result;
};

/*
 * This function is the napi_async_execute_callback.
 *
 * It runs on a worker thread, not on the main JavaScript thread.
 *
 * IMPORTANT:
 * Do NOT use Node-API functions here that execute JavaScript
 * or interact with JavaScript objects.
 *
 * The napi_env parameter is intentionally unused.
 */
void executeSchedule(napi_env env, void* data) {

    // Convert the generic void pointer back to our WorkData structure.
    WorkData* work = static_cast<WorkData*>(data);

    /*
     * Simulate a time-consuming background operation.
     *
     * This is normal C++ code and does not interact with JavaScript.
     */
    std::this_thread::sleep_for(std::chrono::seconds(2));

    // Store the result of the background operation.
    work->result = "Work completed!";
}

/*
 * This function is the napi_async_complete_callback.
 *
 * It runs after the execute callback has finished.
 *
 * This is the appropriate place to use Node-API functions
 * because we are back in the Node.js environment.
 */
void OfflineAudioCompletionEvent(
    napi_env env,
    napi_status status,
    void* data
) {
    // Convert the generic void pointer back to our WorkData structure.
    WorkData* work = static_cast<WorkData*>(data);

    /*
     * Check whether the asynchronous operation completed successfully.
     */
    if (status == napi_ok) {

        // Print the result generated by the background operation.
        std::printf("Result: %s\n", work->result.c_str());
    }

    /*
     * Release the memory allocated when the asynchronous operation
     * was started.
     */
    delete work;
}

/*
 * JavaScript-callable function that starts the asynchronous operation.
 *
 * JavaScript can call:
 *
 *     startAsyncWork();
 */
napi_value StartAsyncWork(napi_env env, napi_callback_info info) {

    // Variable used to return a JavaScript value.
    napi_value result;

    /*
     * Allocate the data that will be passed to both callbacks.
     */
    WorkData* work = new WorkData();

    // Handle representing the asynchronous work item.
    napi_async_work asyncWork;

    /*
     * Create a JavaScript string that identifies the async resource.
     *
     * The resource name is useful for debugging and diagnostics.
     */
    napi_value resourceName;

    napi_create_string_utf8(
        env,
        "ExampleAsyncWork",
        NAPI_AUTO_LENGTH,
        &resourceName
    );

    /*
     * Create the asynchronous work object.
     *
     * Arguments:
     *
     * 1. env
     *    Current N-API environment.
     *
     * 2. nullptr
     *    No async resource object is provided.
     *
     * 3. resourceName
     *    Name used to identify this asynchronous operation.
     *
     * 4. executeSchedule
     *    Function executed on the worker thread.
     *
     * 5. OfflineAudioCompletionEvent
     *    Function executed when the worker operation finishes.
     *
     * 6. work
     *    Custom data passed to both callbacks.
     *
     * 7. &asyncWork
     *    Receives the created async work handle.
     */
    napi_create_async_work(
        env,
        nullptr,
        resourceName,
        executeSchedule,
        OfflineAudioCompletionEvent,
        work,
        &asyncWork
    );

    /*
     * Add the asynchronous work to Node.js's worker queue.
     *
     * Node.js will execute executeSchedule() in the background
     * and then call OfflineAudioCompletionEvent() when it finishes.
     */
    napi_queue_async_work(env, asyncWork);

    /*
     * Return undefined to JavaScript.
     *
     * The actual result will be handled asynchronously later.
     */
    napi_get_undefined(env, &result);

    return result;
}

/*
 * Module initialization function.
 *
 * This function is called when the native addon is loaded by Node.js.
 */
napi_value Init(napi_env env, napi_value exports) {

    // Handle for the JavaScript function we are going to create.
    napi_value fn;

    /*
     * Create a JavaScript function named "startAsyncWork".
     *
     * When JavaScript calls this function,
     * StartAsyncWork() will be executed.
     */
    napi_create_function(
        env,
        "startAsyncWork",
        NAPI_AUTO_LENGTH,
        StartAsyncWork,
        nullptr,
        &fn
    );

    /*
     * Export the function so it can be accessed from JavaScript.
     *
     * JavaScript can then use:
     *
     *     const addon = require("./addon");
     *     addon.startAsyncWork();
     */
    napi_set_named_property(
        env,
        exports,
        "startAsyncWork",
        fn
    );

    return exports;
}

/*
 * Register the native addon initialization function with Node.js.
 *
 * NODE_GYP_MODULE_NAME is provided by node-gyp during compilation.
 */
NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
